export const descriptionCSS: Map<string, string> = new Map([
    ["color", "Culoarea textului"],
    ["background-color", "Defineste culoare de fundal"],
    ["font-size", "Controleaza dimensiunea fontuluiv pentru textul unui element"],
    ["height", "Determina inaltimea elementului"],
    ["width", "Determina latimea elementului"],
    ["z-index", "Determina ordinea de suprapunere a elementelor"],
    ["border", "Adauga chenar in jurul elementului"],
    ["gap", "Spatiul dintre elementele dintr-un container"],
    ["margin", "Spatiu in jurul elementului"],
    ["padding", "Spatiul dintre continut si marginea unui element."],
    ["justify-self", "Specifica modul in care un element individual ar trebui sa se alinieze in interiorul containerului sau pe axa inline (orizontala)."],
    ["align-self", "Specifica modul în care un element individual ar trebui sa se alinieze in interiorul containerului sau pe axa blocului (verticala)."],
    ["justify-content", "Defineste modul in care spatiul ramas intr-un container este distribuit intre si in jurul elementelor flexibile pe axa inline (orizontala)."],
    ["align-content", "Defineste modul in care spatiul ramas intr-un container este distribuit intre si in jurul elementelor flexibile pe axa blocului (verticala)."],
    ["border-color", "Specifice culoarea marginii unui element."],
    ["border-radius", "Rotunjire margine"],
    ["flex-direction", "Directia elementelor flexibile intr-un container."],
    ["flex-flow", "Specifica directia si comportamentul de infasurare a elementelor flexibile intr-un container."],
    ["grid-gap", "Dimensiunea spatiului dintre elementele grilei intr-un container de grila."],
    ["grid-auto-rows", "Dimensiunea randurilor generate automat intr-un container de grila."],
    ["grid-auto-flow", "Specifies modul in care algoritmul de plasare automata plaseaza elementele grilei intr-un container de grila."],
    ["grid-template-rows", "Dimensiunea randurilor definite in mod explicit intr-un container de grila."],
    ["grid-template-columns", "Dimensiunea coloanelor definite in mod explicit intr-un container de grila."],
    ["grid-area", "Dimensiunea si pozitia unui element de grila intr-un layout de grila."],
    ["grid-row", "Liniile grilei pe care un element ar trebui sa le acopere vertical intr-un layout de grila."],
    ["grid-column", "Liniile grilei pe care un element ar trebui sa le acopere orizontal intr-un layout de grila."],
    ["grid-position", "Pozitia unui element de grila intr-un layout de grila."],
    ["type", "Tipul de conținut al elementului."],
    ["font-family", "Specifica familia de fonturi utilizată pentru textul unui element."],
    ["font-weight", "Specifica grosimea fontului pentru textul unui element."],
    ["text-align", "Specifica alinierea orizontală a textului în cadrul unui element."],
    ["line-height", "Specifica inaltimea liniei pentru textul unui element."],
    ["text-decoration", "Stilizarea decorului textului."],
]);