export const descriptionBlock: Map<string, string> = new Map([
    ["document", "Intregul document HTML, include toate celelalte elemente."],
    ["body", "Continutul principal al documentului HTML."],
    ["head", "Contine metadata, cum ar fi titlul paginii."],
    ["footer", "Zona de subsol a unui document sau a unei sectiuni si contine informatii de incheiere sau de referinta."],
    ["form", "Utilizat pentru colectarea de date de la utilizatori."],
    ["div", "Element utilizat pentru gruparea si organizarea altor elemente HTML."],
    ["span", "Utilizat pentru stilizarea sau manipularea unor parti specifice de text."],
    ["paragraph", "Paragraf HTML, utilizat pentru gruparea de texte si paragrafe."],
    ["title", "Titlul paginii HTML, afisat in bara de titlu a browserului sau in rezultatele motorului de cautare."],
    ["br", "Ruptura de linie in interiorul unui paragraf sau al unui text."],
    ["strong", "Text cu o importanta semantica crescuta, adesea stilizat cu font bold."],
    ["u", "Text subliniat, folosit pentru a indica accentuarea sau o linkul vizitat."],
    ["label", "O eticheta asociata unui control de formular."],
    ["input", "Element de intrare in formular, cum ar fi caseta de text, caseta de selectare sau butonul de submit."],
    ["ul", "Lista neordonata HTML, care afiseaza elementele fara o ordine specifica."],
    ["li", "Un element dintr-o lista ordonata sau neordonata."],
    ["ol", "Lista ordonata HTML, care afiseaza elementele intr-o anumita ordine numerica sau alfabetica."],
    ["dl", "Lista de definitii HTML, care consta din perechi de termeni (dt) si definitii (dd)."],
    ["dt", "Denumire asociata unei definitii intr-o lista de definitii HTML."],
    ["dd", "Definitie asociata unui termen intr-o lista de definitii HTML."],
    ["table", "Tabel HTML, care organizeaza datele intr-un format tabular cu coloane si randuri."],
    ["thead", "Antetul unui tabel HTML, care contine capul de coloane."],
    ["tbody", "Corpul unui tabel HTML, care contine continutul principal al tabelului."],
    ["td", "Celula dintr-un tabel HTML, care contine date sau continut."],
    ["th", "celula de antet dintr-un tabel HTML, care contine titlul sau eticheta coloanei"],
    ["tr", "Rand dintr-un tabel HTML, care contine celulele cu date."],
    ["caption", "Descriere sau un titlu pentru un tabel HTML, afisat de obicei deasupra tabelului."],
    ["mark", "Text marcat sau evidentiat in cadrul unui paragraf sau sectiune de text."],
    ["i", "Text cu stil italic pentru a indica accentuare sau pentru a evidentia cuvinte."],
    ["em", "Text cu stil italic pentru a indica o importanta semantica sau o accentuare."],
    ["big", "Text cu dimensiunea fontului marita."],
    ["small", "Text cu dimensiunea fontului micsorata."],
    ["button", "Un buton interactiv care poate fi apasat de utilizator pentru a declansa o actiune."],
    ["option", "O optiune in cadrul unui meniu derulant (select) dintr-un formular HTML."],
    ["select", "Un meniu derulant care permite utilizatorului să selecteze una sau mai multe optiuni."],
    ["nav", "O secțiune a paginii care conține link-uri de navigare sau meniuri."],
    ["main", "Elementul principal al continutului unei pagini, care este distinct si relevat."],
    ["aside", "O sectiune a paginii care contine continut auxiliar sau complementar la conținutul principal."],
    ["section", "O sectiune tematica sau logica a unei pagini."],
    ["header", "Antetul sau partea de sus a unei sectiuni sau pagini."],
    ["article", "Un articol sau continut independent care poate fi distribuit separat de restul paginii."],
    ["figure", "Un continut media, cum ar fi o imagine, grafica sau diagrama, impreuna cu o legenda asociata."],
    ["audio", "Element pentru redarea audio pe o pagina web."],
    ["video", "Element pentru redarea videoclipurilor pe o pagina web."],
    ["img", "Element pentru afisarea unei imagini pe o pagina web."],
    ["figcaption", "Descriere pentru conținutul elementului figure"]
]);